# Generated by Django 5.0.1 on 2024-01-28 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodalert',
            name='recipients',
        ),
        migrations.AddField(
            model_name='floodalert',
            name='recipients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
